import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Patient, CheckIn } from '@/types';

export function exportPatientReport(
  patient: Patient,
  checkins: CheckIn[],
  summary: string
): void {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(13, 148, 136);
  doc.text('Kakeibo Care Ledger', 20, 20);

  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text(`Patient Report — Generated ${new Date().toLocaleDateString()}`, 20, 28);

  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.line(20, 32, 190, 32);

  // Patient Info
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text(patient.name, 20, 42);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Age: ${patient.age} | Condition: ${patient.condition} | Medication: ${patient.medication} (${patient.medicationFrequency})`,
    20,
    50
  );

  if (patient.caregiverName) {
    doc.text(`Emergency Contact: ${patient.caregiverName}`, 20, 56);
  }

  // Risk Status
  const riskY = patient.caregiverName ? 64 : 58;
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text(`Current Risk Status: ${patient.riskStatus.toUpperCase()}`, 20, riskY);

  // Clinical Summary
  const summaryY = riskY + 10;
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text('Clinical Summary', 20, summaryY);

  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const splitSummary = doc.splitTextToSize(summary, 170);
  doc.text(splitSummary, 20, summaryY + 7);

  // Check-in History Table
  const tableStartY = summaryY + 7 + splitSummary.length * 5 + 8;

  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text('Check-in History', 20, tableStartY);

  const tableData = checkins.slice(0, 14).map((c) => [
    c.date,
    c.systolic && c.diastolic ? `${c.systolic}/${c.diastolic}` : '—',
    c.glucose ? `${c.glucose}` : '—',
    c.medicationTaken ? 'Yes' : 'No',
    c.symptoms.filter((s) => s !== 'None').join(', ') || 'None',
    c.riskStatus.toUpperCase(),
  ]);

  autoTable(doc, {
    startY: tableStartY + 4,
    head: [['Date', 'BP', 'Glucose', 'Meds', 'Symptoms', 'Risk']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [13, 148, 136],
      fontSize: 9,
      fontStyle: 'bold',
    },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 25 },
      5: { cellWidth: 18 },
    },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(
    'This report does not constitute medical advice or diagnosis. For clinical review only. Generated by Kakeibo Care Ledger.',
    20,
    pageHeight - 10
  );

  doc.save(`kakeibo-${patient.name.toLowerCase()}-report.pdf`);
}
